### ISSUE TITLE
To-do List - Milestone 1

### ISSUE THREAD

**Issue by GabrielBogo** [UBC-MDS/pyfer#2]
## Due on Tuesday Feb 5
- [x] Finish Proposal Python
- [x] Finish Proposal R
- [x] **Brainstorm** tests
  - [x] `specify` (@liuyuwei169)
  - [x] `generate` (@GabrielBogo)
  - [x] `calculate` (@DavyGuo)
  - [x] `get_ci` (@Makka)

## Due on Thursday Feb 7
- [ ] **Write** tests & documentation
  - [x] Python (@GabrielBogo & @DavyGuo )
  - [x] R (@liuyuwei169 & @makka3)

## Due on Friday Feb 8
- [x] **Write** functions' documentation
  - [x] Python (@GabrielBogo & @DavyGuo )
  - [x] R (@liuyuwei169 & @makka3)
- [x] Contributing.md
- [x] Code of Conduct
- [x] Set up directory structure
  - [x] Python (@GabrielBogo & @DavyGuo )
  - [ ] R (@liuyuwei169 & @makka3)
